[package]
name = 'pallet-stream'
description = 'Manage Stream Entries.'
version = '0.8.0'
authors = ['Dhiway Networks <info@dhiway.com>']
edition = '2021'
license = "GPL-3.0"
homepage = "https://cord.network"
repository = "https://github.com/dhiway/cord"

[[package.metadata.docs.rs]]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41" }

[dev-dependencies]
sp-core = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", features = ["std"]}
sp-keystore = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", features = ["std"]}
pallet-balances = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", features = ["std"]}
cord-utilities = { package = "cord-utilities", path="../../utilities", features = ["mock"] }
sp-io = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", default-features = false, optional = false }

[dependencies]

codec = { package = "parity-scale-codec", version = "3.3.0", default-features = false, features = [
	"derive",
	"max-encoded-len",
] }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
cord-primitives = { package = "cord-primitives", path="../../primitives", default-features = false }
cord-utilities = { package = "cord-utilities", path = "../../utilities", default-features = false }
pallet-registry = {  default-features = false, path = '../registry' }
pallet-schema = {  default-features = false, path = '../schema' }


# Substrate dependencies
frame-support = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", default-features = false }
frame-system = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", default-features = false }
sp-runtime = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", default-features = false }
sp-std = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", default-features = false }
sp-core = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", default-features = false, optional = true }

sp-keystore = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", default-features = false, optional = true}
frame-benchmarking = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.41", default-features = false, optional = true}


[features]
default = [ 'std' ]
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "sp-core",
  "sp-runtime/runtime-benchmarks"
]
std = [
  "codec/std",
  "scale-info/std",
  "frame-support/std",
  "frame-system/std",
  "frame-benchmarking?/std",
  "cord-primitives/std",
  "cord-utilities/std",
  "sp-std/std",
  "sp-runtime/std",
  "pallet-registry/std", 
  "pallet-schema/std", 
  "sp-core/std",
  "sp-keystore/std",
]

try-runtime = [
  "frame-support/try-runtime",
  "frame-system/try-runtime",
  "cord-utilities/try-runtime",
]