[package]
name = 'cord-utilities'
description = "Shared traits and structs"
version = "0.8.0"
authors = ['Dhiway <info@dhiway.com>','BOTLabs GmbH']
edition = '2021'
license = "GPL-3.0"
homepage = "https://cord.network"
repository = "https://github.com/dhiway/cord"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# External dependencies
codec = {default-features = false, features = ["derive"], package = "parity-scale-codec", version = "3.4.0"}
scale-info = {version = "2.1.1", default-features = false, features = ["derive"]}
serde = { version = "1.0.136", features = ["derive"], optional = true }

# Substrate dependencies
frame-support = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.42"}
frame-system = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.42"}
sp-core = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.42"}
sp-runtime = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.42"}
sp-std = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.42"}

[features]
default = ["std"]
mock = []
runtime-benchmarks = [
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
]
std = [
  "codec/std",
  "frame-support/std",
  "frame-system/std",
  "scale-info/std",
  "serde",
  "sp-core/std",
  "sp-runtime/std",
  "sp-std/std",
]
try-runtime = [
  "frame-support/try-runtime",
]
