[package]
name = 'pallet-did-names'
description = "Unique name alias for CORD DIDs."
version = '0.8.0'
authors = ['Dhiway Networks <info@dhiway.com>']
edition = '2021'
license = "GPL-3.0"
homepage = "https://cord.network"
repository = "https://github.com/dhiway/cord"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dev-dependencies]
cord-utilities = { package = "cord-utilities", path = "../../utilities", features = ["mock"] }
pallet-balances = {git = "https://github.com/dhiway/substrate", features = ["std"], branch = "release-v0.9.42"}
sp-core = { git = "https://github.com/dhiway/substrate", features = ["std"], branch = "release-v0.9.42" }
sp-io = { git = "https://github.com/dhiway/substrate", features =["std"], branch = "release-v0.9.42" }
sp-keystore = {git = "https://github.com/dhiway/substrate", features = ["std"], branch = "release-v0.9.42"}

[dependencies]
# External dependencies
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }

# Internal dependencies
cord-utilities = { package = "cord-utilities", path = "../../utilities", default-features = false }

# Substrate dependencies
frame-support = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.42", default-features = false }
frame-system = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.42", default-features = false }
sp-runtime = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.42", default-features = false }
sp-std = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.42", default-features = false }
sp-core = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.42", default-features = false, optional=true }

# Benchmarking dependencies
frame-benchmarking = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.42", default-features = false, optional = true}
sp-io = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.42", default-features = false, optional = true }

[features]
default = ["std"]
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "cord-utilities/runtime-benchmarks",
]
std = [
  "codec/std",
  "scale-info/std",
  "frame-support/std",
  "frame-system/std",
  "frame-benchmarking?/std",
  "sp-runtime/std",
  "sp-core/std",
  "sp-std/std",
]
try-runtime = [
  "frame-support/try-runtime",
  "frame-system/try-runtime",
]
