[package]
name = "pallet-did-runtime-api"
description = "Runtime APIs for dealing with DIDs."
version = '0.8.0'
authors = ['Dhiway <info@dhiway.com>','BOTLabs GmbH']
edition = '2021'
license = "GPL-3.0"
homepage = "https://cord.network"
repository = "https://github.com/dhiway/cord"

[dependencies]
# External dependencies
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }

# Internal dependencies
pallet-did = { package = "pallet-did", path="../../did", default-features = false }

# Substrate 
sp-api = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.42", default-features = false }
sp-std = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.42", default-features = false }

[features]
default = ["std"]
std = [
  "codec/std",
  "sp-api/std",
  "sp-std/std",
  "scale-info/std",
  "pallet-did/std",
]
